version: '3'
services:
  client:
    build: client
    image: loficoffi/munchmunchclient:latest
    ports:
      - '80:80'
  server:
    build: server
    image: loficoffi/munchmunchserver:latest
    environment:
      - PORT=5050
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost:5173
      - ATLAS_URI=mongodb+srv://maxilippmannml:2r8M3Blrkoq3xHl2@munchmunch.ivwixmh.mongodb.net/
    ports:
      - '5050:5050'